### ISSUE TITLE
need clearer title delimiters

### ISSUE THREAD

**Issue by jpcope** [ameswarb/bad-movie-bot#1]
titles with commas in the name can confuse users:

![image](https://cloud.githubusercontent.com/assets/9321688/10834566/595c3790-7e68-11e5-82a8-965c5fee9ce6.png)

**Comment by jpcope** [comment]
recommend stripping the delimiter used in concatenating from the output contents

**Comment by snow0x2d0** [comment]
:hankey:

**Comment by ameswarb** [comment]
changed list delimiters from commas to semicolons in 64cbc61df3fbc09b6f9b0a5aeb87d3216b57bb9c

**Comment by jpcope** [comment]
O Hai John!

**Comment by leviable** [comment]
:shit:

**Comment by jpcope** [comment]
QA never gets any love
